services:
  apache-hotsite:
    build:
      context: .
      dockerfile: Dockerfile
    user: 'root'
    container_name: apps-hotsite
    image: app-hotsite
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - ./html:/var/www/html
      